---
- hosts: nessus
  become: true
  tasks:

  - name: update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: install support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest